id: AD9258657
title: fD041
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:04:56.662856
  last_modified_at: 2022-05-27 15:04:56.662859
