id: AD9258657
title: fA07C
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:04:56.641362
  last_modified_at: 2022-05-27 15:04:56.641365
