id: AD9258657
title: fD10F
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:04:56.664189
  last_modified_at: 2022-05-27 15:04:56.664192
